# Generated by Django 4.1.3 on 2022-11-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=True, upload_to='Service'),
            preserve_default=False,
        ),
    ]
