# Generated by Django 4.1.3 on 2022-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('image', models.ImageField(default='photo_2022-11-06_10-45-19.jpg', null=True, upload_to='Rooms/')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('day', models.CharField(max_length=221)),
            ],
        ),
    ]
