# Generated by Django 4.1.3 on 2022-11-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='day',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='Rooms/'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='hotel.rooms')),
            ],
        ),
    ]
